# Generated by Django 2.2.5 on 2020-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_album_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_short_descr',
            new_name='album_short_des',
        ),
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='album',
            name='album_name',
            field=models.CharField(default='My Album', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(default='My Image', null=True, upload_to=''),
        ),
    ]
