# Generated by Django 2.2.5 on 2020-01-13 19:52

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_auto_20200113_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(null=True, upload_to=Gallery.models.upload_file_directory),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(null=True, upload_to=Gallery.models.upload_file_directory),
        ),
    ]
