# Generated by Django 2.2.5 on 2020-01-20 19:29

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_auto_20200113_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(null=True, upload_to=Gallery.models.upload_image_directory),
        ),
    ]
